# Generated by Django 4.2.3 on 2023-07-27 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('total_votes', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('candidate_a', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_a', to='pollvote.candidates')),
                ('candidate_b', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_b', to='pollvote.candidates')),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pollvote.region')),
            ],
        ),
        migrations.AddField(
            model_name='candidates',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollvote.region'),
        ),
    ]
