# Generated by Django 4.2.3 on 2023-07-27 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pollvote', '0002_pollvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollvote',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollvote.candidates'),
        ),
    ]
